### ISSUE TITLE
Broken interface

### ISSUE THREAD

**Issue by asdfjkl355** [the-paperless-project/paperless#553]
Ive set up paperless on docker.  Attempting to have it reverse proxied to a subdirectory.  Since theres no solid directions I'm attempting to do this myself.  So far I've just gotten this:
![paperless](https://user-images.githubusercontent.com/53507546/62223324-5a11aa80-b37a-11e9-86f6-ff31e0815d66.PNG)

docker-compose.env:
```
PAPERLESS_OCR_LANGUAGES=eng

USERMAP_UID=1000
USERMAP_GID=985

PAPERLESS_FORCE_SCRIPT_NAME=/paperless

PAPERLESS_STATIC_URL=/paperless/static/
PAPERLESS_MEDIA_DIR=/paperless/media/

PAPERLESS_ALLOWED_HOSTS=****.******.com,192.168.1.164,127.0.0.1
PAPERLESS_CORS_ALLOWED_HOSTS=****.******.com,192.168.1.164,127.0.0.1

PAPERLESS_FORGIVING_OCR=true
```

docker-compose.yml:
```
version: '2.1'  

services:
    webserver:
        build: ./
        container_name: paperless_webserver  
        restart: always
        ports:
            - "18000:8000"
        healthcheck:
            test: ["CMD", "curl" , "-f", "http://localhost:18000"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - /media/Scratch-2tb/Configs/Paperless/Data:/usr/src/paperless/data
            - /media/Scratch-2tb/Configs/Paperless/Media:/usr/src/paperless/media
            - /media/Scratch-2tb/Configs/Paperless/Static:/usr/src/paperless/static
            - /media/Scratch-2tb/Configs/Paperless/Consume:/consume
        env_file: docker-compose.env
        environment:
            - PAPERLESS_OCR_LANGUAGES=
        command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]

    consumer:
        build: ./
        container_name: paperless_consumer
        restart: always
        depends_on:
            - webserver
        volumes:
            - /media/Scratch-2tb/Configs/Paperless/Data:/usr/src/paperless/data
            - /media/Scratch-2tb/Configs/Paperless/Media:/usr/src/paperless/media
            - /media/Scratch-2tb/Configs/Paperless/Static:/usr/src/paperless/static
            - /media/Scratch-2tb/Configs/Paperless/Consume:/consume
            - /media/Scratch-2tb/Configs/Paperless/Export:/export  
        env_file: docker-compose.env
        command: ["document_consumer"]
```

relevent section of httpd config:
```
<Location /paperless>
        Order allow,deny
        Allow from all
        ProxyPass http://127.0.0.1:18000/paperless
        ProxyPassReverse http://127.0.0.1:18000/paperless
</Location>
```

Any help would be appreciated. thank you.
