### ISSUE TITLE
Webinterface broken using docker-compose and nginx

### ISSUE THREAD

**Issue by stueja** [the-paperless-project/paperless#660]
I feel I am having a fundamental misunderstanding of how paperless works with docker-compose and nginx; I followed the instructions as good as I could, but still, javascript and css are not served. I appreciate any poke into the correct direction.

I read the existing issues and currently, this issue looks different to me.
#167 : I found `collectstatic` already in docker-compose.yml
#248 : I couldn't find the command "runserver" in docker-compose.yml
#253 : I am deploying in root (paperless.domain.tld); 
#473 : the issue is not using docker

**What I did:**
I cloned the repository, copied and edited the docker-compose files; created and chown'ed folders; 
**docker-compose.yml and .env:**
```
version: '2.1'

services:
    webserver:
        build: ./
        # uncomment the following line to start automatically on system boot
        restart: always
        ports:
            # You can adapt the port you want Paperless to listen on by
            # modifying the part before the `:`.
            - "8000:8000"
        healthcheck:
            test: ["CMD", "curl" , "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - /cloud/jan/files/Dokumente/paperless/data:/usr/src/paperless/data
            - /cloud/jan/files/Dokumente/paperless/media:/usr/src/paperless/media
            # You have to adapt the local path you want the consumption
            # directory to mount to by modifying the part before the ':'.
            - ./consume:/consume
            - /cloud/jan/files/Dokumente/paperless/import-export:/import-export
        env_file: docker-compose.env
        # The reason the line is here is so that the webserver that doesn't do
        # any text recognition and doesn't have to install unnecessary
        # languages the user might have set in the env-file by overwriting the
        # value with nothing.
        environment:
            - PAPERLESS_OCR_LANGUAGES=deu eng
        command: ["gunicorn", "-b", "0.0.0.0:8000"]

    consumer:
        build: ./
        # uncomment the following line to start automatically on system boot
        restart: always
        depends_on:
            webserver:
                condition: service_healthy
        volumes:
            - /cloud/jan/files/Dokumente/paperless/data:/usr/src/paperless/data
            - /cloud/jan/files/Dokumente/paperless/media:/usr/src/paperless/media
            # This should be set to the same value as the consume directory
            # in the webserver service above.
            - ./consume:/consume
            - /cloud/jan/files/Dokumente/paperless/import-export:/import-export
            # Likewise, you can add a local path to mount a directory for
            # exporting. This is not strictly needed for paperless to
            # function, only if you're exporting your files: uncomment
            # it and fill in a local path if you know you're going to
            # want to export your documents.
            # - /path/to/another/arbitrary/place:/export
        env_file: docker-compose.env
        command: ["document_consumer"]

volumes:
    data:
    media:

```

```
# Environment variables to set for Paperless
# Commented out variables will be replaced with a default within Paperless.
#
# In addition to what you see here, you can also define any values you find in
# paperless.conf.example here.  Values like:
#
# * PAPERLESS_PASSPHRASE
# * PAPERLESS_CONSUMPTION_DIR
# * PAPERLESS_CONSUME_MAIL_HOST
#
# ...are all explained in that file but can be defined here, since the Docker
# installation doesn't make use of paperless.conf.

# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
TZ=Europe/Berlin

# Additional languages to install for text recognition.  Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# default language used when guessing the language from the OCR output.
PAPERLESS_OCR_LANGUAGES=deu eng

# Set Paperless to use SSL for the web interface.
# Enabling this will require ssl.key and ssl.cert files in paperless' data directory.
PAPERLESS_USE_SSL=false

# You can change the default user and group id to a custom one
USERMAP_UID=1000
USERMAP_GID=5002

PAPERLESS_INLINE_DOC=true

```

**Then I started docker:**
```
systemctl enable --now docker
docker-compose up -d
docker-compose run --rm webserver createsuperuser
```
When calling https://host.domain.tld:8000/, everything works fine and looks as desired. 

Then I created an **nginx configuration** according to https://paperless.readthedocs.io/en/latest/setup.html#making-things-a-little-more-permanent
```
server {
    listen 80;

    index index.html index.htm index.php;
    access_log /var/log/nginx/paperless_access.log;
    error_log /var/log/nginx/paperless_error.log;

    location /static {

        autoindex on;
        #alias <path-to-paperless-static-directory>;
        #where is that paperless static directory?
        alias /usr/share/docker/paperless/;

    }

    location / {

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://127.0.0.1:8000;
    }
}

```

Note that I don't have a clue how to find the static files.

On the host system, there is a static directory in `src/paperless/static/paperless/`, but it contains only an `img/` directory. Apart from that, no further useful `static` directory.

```
[root@brick paperless]# find . -type d -name static
./src/documents/static
./src/paperless/static
```

`manage.py` seems to have a possibility to collect those static files. But I can't seem to be able to do that:
from the host system:
```
[root@brick paperless]# src/manage.py collectstatic
Traceback (most recent call last):
  File "src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python3.8/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'whitenoise'
```

In the docker container, the static files are already there:
```
[root@brick paperless]# docker exec -it paperless_webserver_1 /bin/bash
bash-5.0# ls -al /usr/src/paperless/static/
total 51
drwxr-sr-x    1 paperles paperles      3488 May 18 22:59 .
drwxr-sr-x    1 paperles paperles      3488 May 18 23:00 ..
drwxr-sr-x    1 paperles paperles      3488 May 18 22:59 admin
drwxr-sr-x    1 paperles paperles      3488 May 18 22:59 django_extensions
drwxr-sr-x    1 paperles paperles      3488 May 18 22:59 djangoql
drwxr-sr-x    1 paperles paperles      3488 May 18 22:59 documents
drwxr-sr-x    1 paperles paperles      3488 May 18 22:59 js
drwxr-sr-x    1 paperles paperles      3488 May 18 22:59 paperless
-rw-r--r--    1 paperles paperles       343 May 18 22:59 paperless.css
-rw-r--r--    1 paperles paperles       155 May 18 22:59 paperless.css.br
-rw-r--r--    1 paperles paperles       209 May 18 22:59 paperless.css.gz
-rw-r--r--    1 paperles paperles       343 May 18 22:59 paperless.ee178b38102f.css
-rw-r--r--    1 paperles paperles       155 May 18 22:59 paperless.ee178b38102f.css.br
-rw-r--r--    1 paperles paperles       209 May 18 22:59 paperless.ee178b38102f.css.gz
drwxr-sr-x    1 paperles paperles      3488 May 18 22:59 rest_framework
-rw-r--r--    1 paperles paperles     14843 May 18 22:59 staticfiles.json
bash-5.0# 

```

So I guess they should be served but aren't. 

Also, I found the static files in docker's overlayfs. Is any of those what I need to tell nginx to serve?
```
[root@brick paperless]# find /var/lib/docker/overlay2/ -type f -name core.js
/var/lib/docker/overlay2/7ad137ac2d50806138ba5bb43ce606714b2d21c43a675cad84350ae829cf6228/diff/usr/src/paperless/static/admin/js/core.js
/var/lib/docker/overlay2/7ad137ac2d50806138ba5bb43ce606714b2d21c43a675cad84350ae829cf6228/merged/usr/lib/python3.8/site-packages/django/contrib/admin/static/admin/js/core.js
/var/lib/docker/overlay2/7ad137ac2d50806138ba5bb43ce606714b2d21c43a675cad84350ae829cf6228/merged/usr/src/paperless/static/admin/js/core.js
/var/lib/docker/overlay2/9b97610e71f17423270c060adc1d7f00bfb3a5f1a908c361238601448d26b7e7/diff/usr/lib/python3.8/site-packages/django/contrib/admin/static/admin/js/core.js
/var/lib/docker/overlay2/9d4fc68f1e8803c009a9fce017e60ecfe3aa18c82811e54ae34bfed1e9dc172a/diff/usr/src/paperless/static/admin/js/core.js
/var/lib/docker/overlay2/30eb5f0f363be9f206e234a7ea4e6c744793776c251f8dce145f0de811bbaed0/diff/usr/src/paperless/static/admin/js/core.js
/var/lib/docker/overlay2/30eb5f0f363be9f206e234a7ea4e6c744793776c251f8dce145f0de811bbaed0/merged/usr/lib/python3.8/site-packages/django/contrib/admin/static/admin/js/core.js
/var/lib/docker/overlay2/30eb5f0f363be9f206e234a7ea4e6c744793776c251f8dce145f0de811bbaed0/merged/usr/src/paperless/static/admin/js/core.js

```

Thank you very much for any hint into a direction :)

**Comment by MasterofJOKers** [comment]
I think, if you want to serve the static files with nginx, you will have to add another volume to the docker container from a local directory. Mount that directory at the right place in the container or change `PAPERLESS_STATICDIR` to where you mounted it, so that `collectstatic` puts its files in there. Then point Nginx to that directory on the outside.

**Comment by stueja** [comment]
@MasterofJOKers , all my gratitude is yours. Thank you, you pushed me into the right direction.
I have read through obscure definitions of volumes, bind-mounts etc and came up with that:
**excerpt from docker-compose.yml**
```
version: '2.1'

services:
    webserver:
        volumes:
            # Publish static files from container to host system so nginx can access it, part 1
            # https://stackoverflow.com/a/52167620/6426489
            - static:/usr/src/paperless/static
    consumer:
[nothing changed in consumer] 

volumes:
    data:
    media:

    # Publish static files from container to host system so nginx can access it, part 2
    #https://stackoverflow.com/a/52167620/6426489
    static:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /usr/share/docker/paperless/static

```

**nginx**
nginx then only needs to be pointed to the directory listed as `device`:
```
server {
        listen 443 ssl http2;
        #listen [::]:443 ssl http2;
        server_name paperless.domain.de;

    index index.html index.htm index.php;
    access_log /var/log/nginx/paperless_access.log;
    error_log /var/log/nginx/paperless_error.log;

    location /static {

        autoindex on;
	# webapps-root
        # alias /usr/share/webapps/paperless/static;
	# docker-root
	alias /usr/share/docker/paperless/static;

    }

    location / {

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
	proxy_hide_header X-Frame-Options;

        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $http_host;
    }
}

```

**Comment by AlexKalopsia** [comment]
Hi @stueja , thank you for the detailed overview on how you fixed this. I got it to work following your guide, but Paperless is failing to load the page styling files. Any idea what could be the cause of this?

**Comment by stueja** [comment]
Hey @AlexKalopsia , welcome.
does the directory `/volume1/docker/paperless/static` exist? Are files in it? Does nginx have access to it?

**Comment by AlexKalopsia** [comment]
@stueja the folder exists, and I can see all the files created with `./manage.py collectstatic'

I am not fully sure how to check if nginx has access to it, though?

**Comment by stueja** [comment]
I'd use something like `sudo -u http cat /volume1/docker/paperless/static/paperless.css`.
Next, you could use your browser's developer tools (F12 usually, I'd then use "Network" and reload paperless) to see whether the browser wants to load those files, e. g. `paperless.css`.
Also, nginx's log files (usually `/var/log/nginx/access.log` and `error.log`) could give a hint on what is going wrong.

**Comment by AlexKalopsia** [comment]
@stueja `cat` returns the content of the css file.

the Network tab just shows a whole lot of 404, so it is trying to load the file but just fails.

The logs don't seem to show anything at all :(

My current config:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name paperless.*;

    include /config/nginx/ssl.conf;

    index index.html index.htm index.php;
    access_log /var/log/nginx/paperless_access.log;
    error_log /var/log/nginx/paperless_error.log;

    location /static {

        autoindex on;
	    # webapps-root
        # alias /usr/share/webapps/paperless/static;
	    # docker-root
	    alias /volume1/docker/paperless/static;

    }

    location / {

        include /config/nginx/proxy.conf;
        #proxy_set_header X-Real-IP $remote_addr;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Forwarded-Proto $scheme;
	    #proxy_hide_header X-Frame-Options;

        proxy_pass http://192.168.1.200:4444;
        #proxy_set_header Host $http_host;
    }
}
``` 

docker-compose:
```
version: "3"
services:

  paperless-webserver:
    container_name: paperless-webserver
    image: thepaperlessproject/paperless:latest
    ports:
      - "4444:8000"
    env_file:
      - /volume1/docker/.env
    environment:
      - PAPERLESS_OCR_LANGUAGES=eng ita swe nld bul
      - PAPERLESS_PASSPHRASE=${PAPER_PSW}
      - PAPERLESS_USE_SSL=true
      - USERMAP_UID=1000
      - USERMAP_GID=1000
      - TZ=${TZ}
    volumes:
      - /volume1/docker/paperless/data:/usr/src/paperless/data
      - /volume1/docker/paperless/media:/usr/src/paperless/media
      - /volume1/docker/paperless/consume:/consume
      - /volume1/docker/paperless/export:/export
      - /volume1/docker/paperless/static:/usr/src/paperless/static
    command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]
    restart: unless-stopped

  paperless-consumer:
    container_name: paperless-consumer
    image: thepaperlessproject/paperless:latest
    environment:
      - PAPERLESS_OCR_LANGUAGES=eng ita swe nld bul
      - PAPERLESS_PASSPHRASE=${PAPER_PSW}
      - PAPERLESS_USE_SSL=true
      - USERMAP_UID=1000
      - USERMAP_GID=1000
      - TZ=${TZ}
    tmpfs:
      - /tmp
    depends_on:
      - paperless-webserver
    volumes:
      - /volume1/docker/paperless/data:/usr/src/paperless/data
      - /volume1/docker/paperless/media:/usr/src/paperless/media
      - /volume1/docker/paperless/consume:/consume
      - /volume1/docker/paperless/export:/export
    command: ["document_consumer"]
    restart: unless-stopped
```
